### ISSUE TITLE
Impossible to create Strange Honey?

### ISSUE THREAD

**Issue by DarkOutX** [InspectorCaracal/BetterBeekeeping#5]
Bees just dying from Wither rose. Is there any way to produce honey? I see the only way to get Strange Honey is to spam Regeneration or Healing explosing potion. But it's too expensive for such reward

**Comment by KoboldCatgirl** [comment]
The bulk of the honey effects are all a little weak, in part because the advantages they grant is so subtle. I think if they granted a period of immunity, or could be used on other creatures, and/or removed some more obscure conditions like the shulker's antigravity, they might feel more worth stocking in place of milk. Strange Honey, in particular, is a massive expense for a fairly subtle benefit. Sure, clearing withering without losing potion effects is great when fighting the wither for the second time, but is it good enough to justify spending hundreds of healing/regen potions and a good chunk of your time? Most people only fight the Wither once anyways, and people who farm it usually trap it.

I think if creating Strange Honey once made bees permanently immune, since, you know, bees do eat their own honey--it might also feel less Sisyphean. Managing it once feels like enough of a chore.

**Comment by InspectorCaracal** [comment]
Thanks for the feedback! However, this is intentional.

The effects of flavored honey in general are intentionally less than potions, since for the normal flavors, once you have a hive set up to produce it, you can make infinite amounts with no additional effort or resources.

> but is it good enough to justify spending hundreds of healing/regen potions and a good chunk of your time?

Nope! :)

Strange honey isn't supposed to be an endgame superhoney - it's designed to be an almost Easter egg kind of thing, because I felt the wither rose needed unique pollen. As such, it has a thematically appropriate but not super strong effect. 

The main point of this mod is to *not* do things that would hurt your bees, so I don't see any reason to make farming wither roses more appealing.
